Depend on adc-streaming pyproject.toml branch
This fixes the following installation error:

```
$ poetry install
Installing dependencies from lock file

Package operations: 0 installs, 11 updates, 0 removals

  • Updating adc-streaming (2.0.1.dev24+gb413e15 -> 2.1.1.dev13+g869b19d 869b19d): Failed

  EnvCommandError

  Command ['/Users/lpsinger/Library/Caches/pypoetry/virtualenvs/gwcelery-uJmssHf_-py3.8/bin/pip', 'install', '--no-deps', '-U', '/Users/lpsinger/Library/Caches/pypoetry/virtualenvs/gwcelery-uJmssHf_-py3.8/src/adc-streaming'] errored with the following return code 1, and output:
  Processing /Users/lpsinger/Library/Caches/pypoetry/virtualenvs/gwcelery-uJmssHf_-py3.8/src/adc-streaming
    DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
     pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
      ERROR: Command errored out with exit status 1:
       command: /Users/lpsinger/Library/Caches/pypoetry/virtualenvs/gwcelery-uJmssHf_-py3.8/bin/python3.8 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/cs/pwq97bws17d2p8qcp410gs7c84mbdz/T/pip-req-build-pp5ik5ce/setup.py'"'"'; __file__='"'"'/private/var/folders/cs/pwq97bws17d2p8qcp410gs7c84mbdz/T/pip-req-build-pp5ik5ce/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/cs/pwq97bws17d2p8qcp410gs7c84mbdz/T/pip-pip-egg-info-o9pggx8k
           cwd: /private/var/folders/cs/pwq97bws17d2p8qcp410gs7c84mbdz/T/pip-req-build-pp5ik5ce/
      Complete output (3 lines):
      Traceback (most recent call last):
        File "<string>", line 1, in <module>
      ModuleNotFoundError: No module named 'setuptools'
      ----------------------------------------
  WARNING: Discarding file:///Users/lpsinger/Library/Caches/pypoetry/virtualenvs/gwcelery-uJmssHf_-py3.8/src/adc-streaming. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  WARNING: You are using pip version 21.2.4; however, version 22.2.2 is available.
  You should consider upgrading via the '/Users/lpsinger/Library/Caches/pypoetry/virtualenvs/gwcelery-uJmssHf_-py3.8/bin/python3.8 -m pip install --upgrade pip' command.

  at ~/.poetry/lib/poetry/utils/env.py:1195 in _run
      1191│                 output = subprocess.check_output(
      1192│                     cmd, stderr=subprocess.STDOUT, **kwargs
      1193│                 )
      1194│         except CalledProcessError as e:
    → 1195│             raise EnvCommandError(e, input=input_)
      1196│
      1197│         return decode(output)
      1198│
      1199│     def execute(self, bin, *args, **kwargs):

```